name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      # Since we don't have a proper way to specify "extension deps" for NetLogo, we have to do this to
      # get them installed stand-alone.  -Jeremy B April 2022
      - run: sbt -v update compile test:compile "test:runMain org.nlogo.workspace.ExtensionInstaller csv table"
      - run: sbt -v test
